// let g = 0;

// setTimeout(() => {
// 	g = 100;
// }, 0);

// console.log(g);

// try {
// 	setTimeout(() => {
// 		throw new Error('에러 발생');
// 	}, 1000);
// } catch (error) {
// 	console.error('내가 에러를 잡을 꺼야!');
// }

// const fulfilled = new Promise((resolve, reject) => resolve(1));

// const rejected = new Promise((resolve, reject) =>
// 	reject(new Error('failure Error'))
// );

// console.log(rejected);
// console.log(fulfilled);

// console.log('start');

// setTimeout(() => console.log('setTimeout'), 0);

// Promise.resolve('Promise').then((res) => console.log(res));

// console.log('End');
